### Importación de datos

In [2]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

#1. Análisis de facturación

In [ ]:
ingresoTotalTienda1 = sum(tienda["Precio"])
print(f'El ingreso total de la tienda 1 es: {ingresoTotalTienda1}')
ingresoTotalTienda2 = sum(tienda2["Precio"])
print(f'El ingreso total de la tienda 2 es: {ingresoTotalTienda2}')
ingresoTotalTienda3 = sum(tienda3["Precio"])
print(f'El ingreso total de la tienda 3 es: {ingresoTotalTienda3}')
ingresoTotalTienda4 = sum(tienda4["Precio"])
print(f'El ingreso total de la tienda 4 es: {ingresoTotalTienda4}')

El ingreso total de la tienda 1 es: 1150880400.0
El ingreso total de la tienda 2 es: 1116343500.0
El ingreso total de la tienda 3 es: 1098019600.0
El ingreso total de la tienda 4 es: 1038375700.0

In [ ]:
tiendaMayorIngreso = max(sum(tienda["Precio"]),sum(tienda2["Precio"]),sum(tienda3["Precio"]),sum(tienda4["Precio"]))
if tiendaMayorIngreso == ingresoTotalTienda1:
  print(f'La tienda 1 cuenta con el mayor ingreso con un monto de: {tiendaMayorIngreso}')
elif tiendaMayorIngreso == ingresoTotalTienda2:
  print(f'La tienda 2 cuenta con el mayor ingreso con un monto de: {tiendaMayorIngreso}')
elif tiendaMayorIngreso == ingresoTotalTienda3:
  print(f'La tienda 3 cuenta con el mayor ingreso con un monto de: {tiendaMayorIngreso}')
elif tiendaMayorIngreso == ingresoTotalTienda4:
  print(f'La tienda 4 cuenta con el mayor ingreso con un monto de: {tiendaMayorIngreso}')

La tienda 1 cuenta con el mayor ingreso con un monto de: 1150880400.0

# 2. Ventas por categoría

In [8]:
agrupacionTienda1 = tienda.groupby("Categoría del Producto")
ventasCategoriaTienda1 = agrupacionTienda1["Categoría del Producto"].count()
print(f'Las ventas por categoria de la tienda 1 son: {ventasCategoriaTienda1}')
agrupacionTienda2 = tienda2.groupby("Categoría del Producto")
ventasCategoriaTienda2 = agrupacionTienda2["Categoría del Producto"].count()
print(f'Las ventas por categoria de la tienda 2 son: {ventasCategoriaTienda2}')
agrupacionTienda3 = tienda3.groupby("Categoría del Producto")
ventasCategoriaTienda3 = agrupacionTienda3["Categoría del Producto"].count()
print(f'Las ventas por categoria de la tienda 3 son: {ventasCategoriaTienda3}')
agrupacionTienda4 = tienda4.groupby("Categoría del Producto")
ventasCategoriaTienda4 = agrupacionTienda4["Categoría del Producto"].count()
print(f'Las ventas por categoria de la tienda 4 son: {ventasCategoriaTienda4}')

Las ventas por categoria de la tienda 1 son: Categoría del Producto
Artículos para el hogar    171
Deportes y diversión       284
Electrodomésticos          312
Electrónicos               448
Instrumentos musicales     182
Juguetes                   324
Libros                     173
Muebles                    465
Name: Categoría del Producto, dtype: int64
Las ventas por categoria de la tienda 2 son: Categoría del Producto
Artículos para el hogar    181
Deportes y diversión       275
Electrodomésticos          305
Electrónicos               422
Instrumentos musicales     224
Juguetes                   313
Libros                     197
Muebles                    442
Name: Categoría del Producto, dtype: int64
Las ventas por categoria de la tienda 3 son: Categoría del Producto
Artículos para el hogar    177
Deportes y diversión       277
Electrodomésticos          278
Electrónicos               451
Instrumentos musicales     177
Juguetes                   315
Libros                     185
Muebles                    499
Name: Categoría del Producto, dtype: int64
Las ventas por categoria de la tienda 4 son: Categoría del Producto
Artículos para el hogar    201
Deportes y diversión       277
Electrodomésticos          254
Electrónicos               451
Instrumentos musicales     170
Juguetes                   338
Libros                     187
Muebles                    480
Name: Categoría del Producto, dtype: int64

In [18]:
agrupacionTienda1 = tienda.groupby("Categoría del Producto")
ventasCategoriaTienda1 = agrupacionTienda1["Categoría del Producto"].count()
print(f'Las ventas por categoria de la tienda 1 son: {ventasCategoriaTienda1.sort_values(ascending=False)}')
agrupacionTienda2 = tienda2.groupby("Categoría del Producto")
ventasCategoriaTienda2 = agrupacionTienda2["Categoría del Producto"].count()
print(f'Las ventas por categoria de la tienda 2 son: {ventasCategoriaTienda2.sort_values(ascending=False)}')
agrupacionTienda3 = tienda3.groupby("Categoría del Producto")
ventasCategoriaTienda3 = agrupacionTienda3["Categoría del Producto"].count()
print(f'Las ventas por categoria de la tienda 3 son: {ventasCategoriaTienda3.sort_values(ascending=False)}')
agrupacionTienda4 = tienda4.groupby("Categoría del Producto")
ventasCategoriaTienda4 = agrupacionTienda4["Categoría del Producto"].count()
print(f'Las ventas por categoria de la tienda 4 son: {ventasCategoriaTienda4.sort_values(ascending=False)}')

Las ventas por categoria de la tienda 1 son: Categoría del Producto
Muebles                    465
Electrónicos               448
Juguetes                   324
Electrodomésticos          312
Deportes y diversión       284
Instrumentos musicales     182
Libros                     173
Artículos para el hogar    171
Name: Categoría del Producto, dtype: int64
Las ventas por categoria de la tienda 2 son: Categoría del Producto
Muebles                    442
Electrónicos               422
Juguetes                   313
Electrodomésticos          305
Deportes y diversión       275
Instrumentos musicales     224
Libros                     197
Artículos para el hogar    181
Name: Categoría del Producto, dtype: int64
Las ventas por categoria de la tienda 3 son: Categoría del Producto
Muebles                    499
Electrónicos               451
Juguetes                   315
Electrodomésticos          278
Deportes y diversión       277
Libros                     185
Artículos para el hogar    177
Instrumentos musicales     177
Name: Categoría del Producto, dtype: int64
Las ventas por categoria de la tienda 4 son: Categoría del Producto
Muebles                    480
Electrónicos               451
Juguetes                   338
Deportes y diversión       277
Electrodomésticos          254
Artículos para el hogar    201
Libros                     187
Instrumentos musicales     170
Name: Categoría del Producto, dtype: int64

# 3. Calificación promedio de la tienda

In [22]:
calificacionPromedioTienda1 = tienda['Calificación'].mean()
print(f'La calificación promedio de la tienda 1 es: {calificacionPromedioTienda1}')
calificacionPromedioTienda2 = tienda2['Calificación'].mean()
print(f'La calificación promedio de la tienda 2 es: {calificacionPromedioTienda2}')
calificacionPromedioTienda3 = tienda3['Calificación'].mean()
print(f'La calificación promedio de la tienda 3 es: {calificacionPromedioTienda3}')
calificacionPromedioTienda4 = tienda4['Calificación'].mean()
print(f'La calificación promedio de la tienda 4 es: {calificacionPromedioTienda4}')

La calificación promedio de la tienda 1 es: 3.976685036032217
La calificación promedio de la tienda 2 es: 4.037303942348453
La calificación promedio de la tienda 3 es: 4.048325561678677
La calificación promedio de la tienda 4 es: 3.9957591178965224

# 4. Productos más y menos vendidos

In [27]:
productosVendidosTienda1 = tienda.groupby("Producto")
ventasProductosTienda1 = productosVendidosTienda1["Producto"].count()
print(f'Las ventas por producto de la tienda 1 son: {ventasProductosTienda1.sort_values(ascending=False)}')
productosVendidosTienda2 = tienda2.groupby("Producto")
ventasProductosTienda2 = productosVendidosTienda2["Producto"].count()
print(f'Las ventas por producto de la tienda 2 son: {ventasProductosTienda2.sort_values(ascending=False)}')
productosVendidosTienda3 = tienda3.groupby("Producto")
ventasProductosTienda3 = productosVendidosTienda3["Producto"].count()
print(f'Las ventas por producto de la tienda 3 son: {ventasProductosTienda3.sort_values(ascending=False)}')
productosVendidosTienda4 = tienda4.groupby("Producto")
ventasProductosTienda4 = productosVendidosTienda4["Producto"].count()
print(f'Las ventas por producto de la tienda 4 son: {ventasProductosTienda4.sort_values(ascending=False)}')

Las ventas por producto de la tienda 1 son: Producto
Armario                        60
TV LED UHD 4K                  60
Microondas                     60
Secadora de ropa               58
Mesa de noche                  56
Bloques de construcción        56
Balón de baloncesto            55
Bicicleta                      54
Impresora                      54
Vaso térmico                   54
Refrigerador                   54
Batería                        53
Cubertería                     52
Carrito de control remoto      52
Modelado predictivo            51
Auriculares                    50
Ajedrez de madera              49
Iphone 15                      49
Lavavajillas                   48
Guitarra eléctrica             47
Lavadora de ropa               47
Silla de oficina               46
Sofá reclinable                46
Guitarra acústica              46
Estufa                         45
Mesa de centro                 44
Kit de bancas                  44
Cama box                       44
Cubo mágico 8x8                44
Smart TV                       44
Cama king                      44
Juego de mesa                  43
Smartwatch                     43
Set de ollas                   43
Dashboards con Power BI        42
Tablet ABXY                    42
Balón de voleibol              42
Sillón                         41
Iniciando en programación      41
Set de vasos                   41
Asistente virtual              40
Dinosaurio Rex                 40
Cuerda para saltar             40
Muñeca bebé                    40
Mesa de comedor                40
Ciencia de datos con Python    39
Mochila                        39
Pandereta                      36
Olla de presión                35
Celular ABXY                   33
Auriculares con micrófono      33
Name: Producto, dtype: int64
Las ventas por producto de la tienda 2 son: Producto
Iniciando en programación      65
Microondas                     62
Batería                        61
Pandereta                      58
Guitarra acústica              58
Secadora de ropa               57
Iphone 15                      55
Bloques de construcción        54
Armario                        54
Set de ollas                   52
Cuerda para saltar             50
Lavadora de ropa               49
Refrigerador                   49
Silla de oficina               49
Muñeca bebé                    48
Vaso térmico                   47
Cama box                       47
Carrito de control remoto      47
Guitarra eléctrica             47
Balón de voleibol              46
Modelado predictivo            46
Lavavajillas                   46
Set de vasos                   46
Kit de bancas                  45
TV LED UHD 4K                  45
Mochila                        45
Mesa de centro                 45
Cubo mágico 8x8                45
Bicicleta                      45
Ajedrez de madera              45
Cama king                      45
Sofá reclinable                44
Mesa de noche                  44
Olla de presión                44
Auriculares con micrófono      44
Tablet ABXY                    44
Smartwatch                     44
Dashboards con Power BI        43
Ciencia de datos con Python    43
Balón de baloncesto            42
Dinosaurio Rex                 42
Estufa                         42
Celular ABXY                   41
Smart TV                       40
Cubertería                     39
Asistente virtual              38
Auriculares                    37
Sillón                         35
Impresora                      34
Mesa de comedor                34
Juego de mesa                  32
Name: Producto, dtype: int64
Las ventas por producto de la tienda 3 son: Producto
Kit de bancas                  57
Mesa de comedor                56
Cama king                      56
Set de ollas                   55
Mesa de noche                  55
Smart TV                       54
Modelado predictivo            53
Cuerda para saltar             53
Estufa                         53
Carrito de control remoto      52
Juego de mesa                  52
Lavavajillas                   52
Bicicleta                      52
Pandereta                      51
Balón de baloncesto            50
Refrigerador                   50
Impresora                      50
Armario                        49
Balón de voleibol              48
Tablet ABXY                    48
Olla de presión                47
Sillón                         47
Ajedrez de madera              47
Guitarra acústica              47
Smartwatch                     46
Iphone 15                      46
Silla de oficina               46
Iniciando en programación      46
Cama box                       46
Ciencia de datos con Python    46
Dinosaurio Rex                 46
Sofá reclinable                45
Secadora de ropa               45
Celular ABXY                   44
Cubo mágico 8x8                44
Auriculares                    43
Lavadora de ropa               42
TV LED UHD 4K                  42
Mesa de centro                 42
Batería                        41
Dashboards con Power BI        40
Auriculares con micrófono      39
Asistente virtual              39
Muñeca bebé                    39
Cubertería                     39
Vaso térmico                   38
Guitarra eléctrica             38
Mochila                        36
Microondas                     36
Set de vasos                   36
Bloques de construcción        35
Name: Producto, dtype: int64
Las ventas por producto de la tienda 4 son: Producto
Cama box                       62
Cubertería                     59
Cama king                      56
Dashboards con Power BI        56
Carrito de control remoto      55
Mesa de noche                  55
Mesa de comedor                55
Bloques de construcción        54
Smart TV                       54
Pandereta                      52
Asistente virtual              50
Balón de baloncesto            50
Impresora                      50
Set de ollas                   50
Modelado predictivo            50
Iphone 15                      48
Balón de voleibol              48
Batería                        48
Juego de mesa                  48
Muñeca bebé                    48
Microondas                     48
Vaso térmico                   48
Cubo mágico 8x8                47
Estufa                         47
Sofá reclinable                47
Dinosaurio Rex                 47
Olla de presión                46
Set de vasos                   46
Sillón                         45
Tablet ABXY                    45
Bicicleta                      45
Auriculares                    44
Mesa de centro                 44
Mochila                        43
Cuerda para saltar             43
Lavavajillas                   43
Iniciando en programación      43
Auriculares con micrófono      42
Kit de bancas                  42
TV LED UHD 4K                  40
Silla de oficina               40
Secadora de ropa               40
Celular ABXY                   39
Ajedrez de madera              39
Smartwatch                     39
Lavadora de ropa               38
Ciencia de datos con Python    38
Refrigerador                   38
Guitarra acústica              37
Armario                        34
Guitarra eléctrica             33
Name: Producto, dtype: int64

# 5. Envío promedio por tienda

In [31]:
envioPromedioTienda1 = tienda['Costo de envío'].mean()
print(f'El envío promedio de la tienda 1 es: {envioPromedioTienda1}')
envioPromedioTienda2 = tienda2['Costo de envío'].mean()
print(f'El envío promedio de la tienda 2 es: {envioPromedioTienda2}')
envioPromedioTienda3 = tienda3['Costo de envío'].mean()
print(f'El envío promedio de la tienda 3 es: {envioPromedioTienda3}')
envioPromedioTienda4 = tienda4['Costo de envío'].mean()
print(f'El envío promedio de la tienda 4 es: {envioPromedioTienda4}')

El envío promedio de la tienda 1 es: 26018.60958033065
El envío promedio de la tienda 2 es: 25216.235693090293
El envío promedio de la tienda 3 es: 24805.680373039424
El envío promedio de la tienda 4 es: 23459.457167090754